Org Units
common-fate/docs pull request #130
Opened 2022-10-25 02:20 UTC by jordiup

Docs for Org Unit Access Rules

![localhost_3002_granted-approvals_configuration_waf](https://user-images.githubusercontent.com/21688404/197666710-db34672f-9951-419b-ae1e-f340d757ea1c.png)

2022-10-25 17:34 UTC, chrnorm commented on docs/approvals/configuration/org-units.md
> +# AWS Organizational Unit Access
Let's use either "Organizational Unit" or "OU" in our docs. "Org Unit" feels jargony. I've fixed this in the new pages.

2022-10-25 17:59 UTC, chrnorm requested changes
@jordiup these docs are a good start! You've given a great overview on what org units are and I love the OU diagram that you've included. I have some structural feedback to improve this guide. My main concern is that we are describing how OUs work generally, and we aren't describing how Granted Approvals works with OUs. I've suggested some changes to the doc here for you to work through to improve this.

2022-10-25 17:59 UTC, chrnorm commented on docs/approvals/configuration/org-units.md
> +sidebar_position: 11
Can you shift this page into `/docs/approvals/providers/aws-sso/org-units`?

The configuration section should only be for docs on configuring the entire Granted deployment, and this is provider-specific documentation.

2022-10-25 17:59 UTC, chrnorm commented on docs/approvals/configuration/org-units.md
> +OUs allow you to group accounts by business unit, project, or any other criteria you choose. In Granted Approvals this means less work for you. You can grant access to all accounts within an OU and n
Why does it mean less work for you?

```suggestion
Granted Approvals automatically updates the available accounts when OUs are used in Access Rules.

For example, if you wish to allow team members to request access to any production account, you can create a Production OU in your AWS organization. In Granted, you can set up an Access Rule specifying the Production OU.

(@jordiup  - ADD EXAMPLE SCREENSHOT HERE)

When new accounts are added to the Production OU, they will automatically be made available for users to request access to under the same Access Rule. Granted Approvals syncs the available accounts every 5 minutes.
```

2022-10-25 17:59 UTC, chrnorm commented on docs/approvals/configuration/org-units.md
> +The Root OU is the top level of your organization. It is the parent of all other OUs. It is the only OU that can have accounts directly attached to it. All other OUs must be a child of another OU. By
Add a sentence here like - "in Granted Approvals, the Root OU is shown as 'Root' when selecting an OU for an Access Rule", perhaps with a screenshot

2022-10-25 17:59 UTC, chrnorm commented on docs/approvals/configuration/org-units.md
> +## Getting Started
Add a requirements callout to this guide - the user needs to have the `commonfate/aws-sso` Access Provider configured for their deployment.

2022-10-25 17:59 UTC, chrnorm commented on docs/approvals/configuration/org-units.md
> +By selecting an OU it will add all accounts within that OU. You can also add accounts and OUs at the same time.
"it will add all accounts within that OU" can be made a bit more concise - the accounts are automatically synced, rather than manually matched. This phrasing makes it seem like the OU feature is a "select all" button which doesn't sync things.

```suggestion
Granted Approvals will show you a preview of what accounts will be available for selection by Granted Approvals end users. You can also add individual accounts and OUs at the same time.
```

2022-10-25 17:59 UTC, chrnorm commented on docs/approvals/configuration/org-units.md
> +Selecting a Permission Set will reduce the access scope of the accounts you have selected to that permission set. If you select multiple permission sets, the requesting user can select one of those p
Not relevant/needed for this docs page IMO

```suggestion
```

2022-10-25 17:59 UTC, chrnorm commented on docs/approvals/configuration/org-units.md
> +## How do I setup an OU in my AWS account?
This section needs to be modified a little bit to walk through how to use OUs with Granted Approvals, rather than how to use OUs in general. If users want to read about how to use OUs in general, AWS's docs are already good for that!

A good pattern to follow is the guide I wrote for the WAF deployment: https://docs.commonfate.io/granted-approvals/configuration/waf.

The pattern here to use is:
- Do an action
- See the change in Granted Approvals

This allows the users to build a deep understanding of the feature quickly.

In this example, this should be changed to:

1. Deploy an OU in your account
2. Create an Access Rule in Granted Approvals - see that the OU is available for selection
3. Create an account in the OU
4. Check Granted Approvals - see that the account is available for selection

The guide you've written is very close! But it's missing the steps where the users check their Granted Approvals deployment, which make it a lot more understandable and less of a general guide.

2022-10-25 17:59 UTC, chrnorm commented on docs/approvals/configuration/org-units.md
> +aws organizations create-organizational-unit --parent-id <root-ou-id> --name "Engineering"
These steps are out of order. The root OU ID is needed for this command, so users should run `aws organizations list-roots` first.

We can also make this easier for users to run. I am a big fan of the AWS CLI's [`--query` filtering](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-filter.html) as it allows us to build a one-liner that users can copy/paste to run through the docs super fast.

```suggestion
ROOT_OU_ID=$(aws organizations list-roots --query "Roots[0].Id" --output text)
aws organizations create-organizational-unit --parent-id $ROOT_OU_ID --name "Engineering"
```

2022-10-25 17:59 UTC, chrnorm commented on docs/approvals/configuration/org-units.md
> +To [create an account](https://docs.aws.amazon.com/cli/latest/reference/organizations/create-account.html) in your OU you can use the following command:
This should be more instructional and less informational - we're trying to guide the user through a set of predefined steps so they can see the value in OU access.

```suggestion
Create an account in your OU by running the following command:
```

2022-10-25 17:59 UTC, chrnorm commented on docs/approvals/configuration/org-units.md
> +aws organizations create-account --email <email> --account-name <account-name> --role-name <role-name> --iam-user-access-to-billing ALLOW --parent-id <ou-id>
suggestions here - remove the optional variables (looks like AWS's defaults are fine and it adds cognitive overhead for users). Also, push the fields that you want users to edit towards the end of the command so it's easier for them to go backwards with their keyboard to edit it.

```suggestion
aws organizations create-account --account-name ApprovalsTestAccount --parent-id <ou-id> --email <email>
```

2022-10-25 17:59 UTC, chrnorm commented on docs/approvals/configuration/org-units.md
> +If you no longer need an OU you can delete it using the AWS CLI. You can read more about the CLI [here](https://docs.aws.amazon.com/cli/latest/reference/organizations/delete-organizational-unit.html)
This needs to be instructive rather than informational - the steps in this section should be:

1. Archive the Access Rule in your Granted Approvals deployment
2. Delete the AWS account that you created
3. Delete the AWS OU that you created

The section should take users back to the state that their account and deployment was in prior to running the guide, but they now have all the knowledge on how OU access works.

2022-10-25 17:59 UTC, chrnorm commented on docs/approvals/configuration/org-units.md
> +You can find the OU ID by running the following command:
These commands are mixed up again - the OU ID needs to come from the second command you've listed below. So the second command needs to be moved above the first, and use `--query` to find the name as a one-liner.

2022-10-25 18:07 UTC, chrnorm commented on docs/approvals/configuration/org-units.md
> +You will see three fields: Accounts, Organizational Units and Permission Sets. By selecting an account it will be individuall added to the list of accounts.
```suggestion
You will see three fields: Accounts, Organizational Units and Permission Sets. By selecting an account it will be individually added to the list of accounts.
```

2022-10-26 01:39 UTC, cmddx commented
Thanks for putting this together @jordiup! great work, especially in love with the diagram.

Once Chris' suggestions have been worked in I can do a quick pass for sentence structure. In general I think we should lean towards simpler English (replacing "you will" with just "you'll", etc.) so that it's less of a mental effort to read.

2022-10-26 03:28 UTC, jordiup commented on docs/approvals/configuration/org-units.md
> +If you no longer need an OU you can delete it using the AWS CLI. You can read more about the CLI [here](https://docs.aws.amazon.com/cli/latest/reference/organizations/delete-organizational-unit.html)
Cheers Chris, have added in these steps

2022-10-26 08:44 UTC, chrnorm approved these changes

2022-10-26 08:45 UTC, chrnorm commented on docs/approvals/providers/aws-sso/01-org-units.md
> +sidebar_position: 11
```suggestion
slug: org-units
sidebar_position: 11
```

2022-10-26 11:21 UTC, merged