update profile registry doc
common-fate/docs pull request #174
Opened 2022-12-21 05:12 UTC by Eddie023

2022-12-22 07:32 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +granted registry add -n <registry_name> -u <repository_url>
```suggestion
granted registry add -name <registry_name> -u <repository_url>
```

2022-12-22 07:35 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +| requiredKey               | r     | used to bypass the prompt or override user specific values                  |
```suggestion
| `-path`                      | `-p`     | provide path if only the subfolder needs to be synced                       |
| `-filename`                  | `-f`     | provide filename if yml file is not granted.yml                             |
| `-priority`                  |       | profile registry will be sorted by priority descending                      |
| `-prefix-all-profiles`       | `-pap`   | provide this flag if you want to append registry name to all `-profiles`       |
| `-prefix-duplicate-profiles` | `-pdp`   | provide this flag if you want to append registry name to duplicate profiles |
| `-requiredKey`               | `r`     | used to bypass the prompt or override user specific values                  |
```

2022-12-22 07:37 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +| requiredKey               | r     | used to bypass the prompt or override user specific values                  |
@Eddie023 there needs to be some consistency across multi-word flags here. Currently we have things like 
- filename
- prefix-all-profiles
- requiredKey

Please choose one option ie fileName, prefixAllProfiles, requiredKey. I don't have a preference for which.

2022-12-22 07:40 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +This lets users define which profile should have a registry name as prefix on profile duplication.
```suggestion
When multiple registries are in use, registries are synced in descending priority where the default priority is zero. This allows you to define which profile registry is prefixed upon duplication. 
```

2022-12-22 07:46 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +For example if you have Profile Registries A and B with shared profile name `develop` then profile with lower pririty will be prefixed with registry name.
```suggestion
For example, you have Profile Registries `core` and `devops` that both include a profile named `developer`. Profile Registry `core` is prefixed 0 and Profile Registry `devops`, 1. The result of this is the `developer` profile within the `devops` Profile Registry will be prefixed with the registry name `devops`.
```

2022-12-22 07:50 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +If you want to template your AWS profile for user specific values or some re-useability then you can add `templateValues` in your config.yml file like:
```suggestion
To enable templated profiles, profile values can include variable parameters. This is achieved through adding `templateValues` to your `config.yml` file. Below is an example:```

2022-12-22 09:47 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +:::info
@Eddie023 I'm not quite sure I understand what this point is trying to achieve, could you provide some further context?

2022-12-22 09:48 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +## Optional Flags when Adding a Profile Registry
```suggestion
## Optional flags when adding a Profile Registry
```

2022-12-22 09:49 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +### Deterministic Deduplication Priority
```suggestion
### Duplicate profile names
```

2022-12-22 09:50 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +## Variable Substitution in AWS profile
```suggestion
## Variable substitution for profile parameters
```

2022-12-22 09:50 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +### User Specific Values
```suggestion
### User specific values 
```

2022-12-22 09:56 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +1. Add your template variable to config.yml file like:
```suggestion
Should your Profile Registry require user specific values, you can set these values as required fields. You can achieve this by adding `isRequired:true` to the key name of the field. Below is an example `config.yml` file:

```

2022-12-22 09:56 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +Your config file might look like:
```suggestion
The above will output a profile that looks something like this:
```

2022-12-22 10:00 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +This will prompt user to add value for `SessionName` when granted registry add/sync command is run and will interpolate the template with the user provided value.
```suggestion
The inclusion of `.Required` will prompt the user to add the value for `SessionName` when the `granted registry add/sync` command is run. Upon successful execution, Granted will interpolate the template to the AWS config file with the user provided value.
```

2022-12-22 10:01 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +You can bypass the prompt by providing `-r` flag to granted registry add like: <br/>
```suggestion
You can bypass the prompt by providing the `-r` flag to the Granted CLI command:

```
granted registry add -n <name> -u <url> -r "SessionName=<your_session_name>"
```
```

2022-12-22 10:06 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +:::info
```suggestion
:::info
You can bypass the prompt by providing the `-r` flag to the Granted CLI command:
`granted registry add -n <name> -u <url> -r "SessionName=<your_session_name>"`

:::info
```

2022-12-22 10:07 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +### Arbitary variables
```suggestion
### Arbitrary variables 
```

2022-12-22 10:09 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +  - <YourKeyName>
```suggestion
  - <your_key_name>
```

2022-12-22 10:11 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +1. Add your template variable to config.yml file like:
```suggestion
For cases where you want to reuse a variable within a config file, you can add `value` to any key name in `templateValues`. Below is an example `config.yml` file:
```

2022-12-22 10:11 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +Your config file might look like:
```suggestion
The above will output a profile that looks something like this:
```

2022-12-22 10:18 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +Instead the syncing will fail. This occurs as AWS expects only specific JSON STDOUT when configured with sourcing credentials with an external process. You cannot ask user to enter required keys. You
```suggestion
When using AWS CLI with `granted credential-process` you will not be able to add user specific keys through STDIO. Doing so will cause the sync to fail. This occurs as AWS expects only specific JSON STDOUT when sourcing credentials via an external process. Instead, you should first run the following command to enter the required keys:

```bash
granted registry sync
```

2022-12-22 10:21 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +## Migrating Profile Registry Configuration
```suggestion
## Migrating Profile Registry configuration
```

2022-12-22 10:27 UTC, ellie-narducci commented on docs/granted/usage/profile-registry.md
> +Previously, Profile Registry didn't require passing `-n` or `-u` flag. However, the current version has some breaking changes so if you are already using Granted Profile Registry then run the followi
```suggestion
As part of [Granted v0.5.0](https://github.com/common-fate/granted/releases/tag/v0.5.0), the Profile Registry didn't require the `-n` or `-u` flags. [Granted v0.5.3](https://github.com/common-fate/granted/releases/tag/v0.5.3) includes breaking changes to this. If you are using a version of Profile Registries prior to Granted v0.5.3, run the following command to migrate your registry configuration:
```

2022-12-22 10:27 UTC, ellie-narducci requested changes
@Eddie023 some suggested changes already in there for you to approve and a couple comments.

2022-12-23 05:40 UTC, Eddie023 commented on docs/granted/usage/profile-registry.md
> +  - <YourKeyName>
@ellie-narducci  I didn't update this one because Go templates are generally added as PascalCase and these keys should be same as values in templates like `{{.Required.SessionName}}`

2022-12-30 10:25 UTC, merged